/**
 * generated by Xtext 2.12.0
 */
package org.xtext.entites.entites.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.entites.entites.ui.AbstractEntitiesUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EntitiesUiModule extends AbstractEntitiesUiModule {
  public EntitiesUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
