/**
 * generated by Xtext 2.12.0
 */
package org.xtext.entites.entites.ide;

import org.xtext.entites.entites.ide.AbstractEntitiesIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EntitiesIdeModule extends AbstractEntitiesIdeModule {
}
