/**
 * generated by Xtext 2.12.0
 */
package org.xtext.entites.entites;

import org.xtext.entites.entites.AbstractEntitiesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EntitiesRuntimeModule extends AbstractEntitiesRuntimeModule {
}
